/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OORestaurants;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;






/**
 *
 * @author C ABHICHANDAN GOUD
 */
public class OO_Restaurants extends javax.swing.JFrame {

    /**
     * Creates new form OO_Restaurants
     */
    public OO_Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlblMeals = new javax.swing.JLabel();
        jlblFiletOFish = new javax.swing.JLabel();
        jlblChickenBurger = new javax.swing.JLabel();
        jlblChickenLegend = new javax.swing.JLabel();
        jlblChickenBurgerMeal = new javax.swing.JLabel();
        jlblBaconandCheeseBurger = new javax.swing.JLabel();
        jtxtChickenLegend = new javax.swing.JTextField();
        jtxtChickenBurger = new javax.swing.JTextField();
        jtxtFiletofFish = new javax.swing.JTextField();
        jtxtChickenBurgerM = new javax.swing.JTextField();
        jtxtBaconandCheeseBurger = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jlblVanillaMilkShake = new javax.swing.JLabel();
        jlblClassicVanilla = new javax.swing.JLabel();
        jtxtMilkShake = new javax.swing.JTextField();
        jtxtVanillaCone = new javax.swing.JTextField();
        jtxtChocMilkShake = new javax.swing.JTextField();
        jlblDrinks = new javax.swing.JLabel();
        jlblVanillaCone = new javax.swing.JLabel();
        jlblMilkShake = new javax.swing.JLabel();
        jtxtVanMilkShake = new javax.swing.JTextField();
        jtxtClasVanilla = new javax.swing.JTextField();
        jlblChocolateMilkShake = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextPane();
        jPanel9 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jlblTax2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jbtnTotal = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jlblCostofMeal = new javax.swing.JLabel();
        jlblCostofDrinks = new javax.swing.JLabel();
        jiblTotalCostofItems = new javax.swing.JLabel();
        jtxtCostMeal = new javax.swing.JTextField();
        jtxtcostofDrinks = new javax.swing.JTextField();
        jtxtTotalCostofItems = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Restaurant Management System");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 160));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblMeals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblMeals.setText("Meals");

        jlblFiletOFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblFiletOFish.setText("Filet-O-Fish");

        jlblChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblChickenBurger.setText("Chicken Burger");

        jlblChickenLegend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblChickenLegend.setText("Chicken Legend");

        jlblChickenBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblChickenBurgerMeal.setText("Chicken Burger Meal");

        jlblBaconandCheeseBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblBaconandCheeseBurger.setText("Bacon and Cheese Burger");

        jtxtChickenLegend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtChickenLegend.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenLegend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenLegendActionPerformed(evt);
            }
        });

        jtxtChickenBurger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtChickenBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenBurgerActionPerformed(evt);
            }
        });

        jtxtFiletofFish.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtFiletofFish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFiletofFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFiletofFishActionPerformed(evt);
            }
        });

        jtxtChickenBurgerM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtChickenBurgerM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurgerM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenBurgerMActionPerformed(evt);
            }
        });

        jtxtBaconandCheeseBurger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtBaconandCheeseBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBaconandCheeseBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBaconandCheeseBurgerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jlblMeals))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblFiletOFish, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblChickenLegend, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblChickenBurgerMeal))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblBaconandCheeseBurger)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtChickenLegend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxtChickenBurger)
                        .addComponent(jtxtFiletofFish, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addComponent(jtxtChickenBurgerM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtBaconandCheeseBurger, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlblMeals)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlblFiletOFish)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblChickenBurger)))
                    .addComponent(jtxtFiletofFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblChickenLegend)
                    .addComponent(jtxtChickenLegend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblChickenBurgerMeal)
                    .addComponent(jtxtChickenBurgerM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblBaconandCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtBaconandCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 510, 340));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblVanillaMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblVanillaMilkShake.setText("Vanilla Milk Shake");

        jlblClassicVanilla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblClassicVanilla.setText("Classic Vanilla");

        jtxtMilkShake.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMilkShakeActionPerformed(evt);
            }
        });

        jtxtVanillaCone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtVanillaCone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanillaCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVanillaConeActionPerformed(evt);
            }
        });

        jtxtChocMilkShake.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtChocMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChocMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChocMilkShakeActionPerformed(evt);
            }
        });

        jlblDrinks.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblDrinks.setText("Drinks");

        jlblVanillaCone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblVanillaCone.setText("Vanilla Cone");

        jlblMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblMilkShake.setText("Milk Shake");

        jtxtVanMilkShake.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtVanMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVanMilkShakeActionPerformed(evt);
            }
        });

        jtxtClasVanilla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtClasVanilla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtClasVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtClasVanillaActionPerformed(evt);
            }
        });

        jlblChocolateMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblChocolateMilkShake.setText("Chocolate Milk Shake");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jlblDrinks)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblVanillaCone, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblClassicVanilla)
                    .addComponent(jlblVanillaMilkShake)
                    .addComponent(jlblChocolateMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxtVanMilkShake, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addComponent(jtxtClasVanilla, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtMilkShake, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtChocMilkShake))
                    .addComponent(jtxtVanillaCone, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlblDrinks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMilkShake)
                    .addComponent(jtxtMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtVanillaCone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblVanillaCone))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblClassicVanilla)
                            .addComponent(jtxtClasVanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtVanMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlblVanillaMilkShake)))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblChocolateMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtChocMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 480, 340));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 450, 590));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal.setText("SubTotal");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setText("Total");

        jlblTax2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax2.setText("Tax");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTax2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(jtxtSubTotal)
                    .addComponent(jtxtTotal))
                .addGap(56, 56, 56))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTax2)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jlblSubTotal))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jtxtSubTotal)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlblTotal))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 480, 150));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTotal.setForeground(new java.awt.Color(51, 51, 0));
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(51, 51, 0));
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(51, 51, 0));
        jbtnExit.setText("Exit");
        jbtnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReceipt.setForeground(new java.awt.Color(51, 51, 0));
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(jbtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTotal)
                    .addComponent(jbtnReceipt)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1000, 80));

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblCostofMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostofMeal.setText("Cost of Meal");

        jlblCostofDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostofDrinks.setText("Cost of Drinks");

        jiblTotalCostofItems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jiblTotalCostofItems.setText("Total Cost of Items");

        jtxtCostMeal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtCostMeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCostMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostMealActionPerformed(evt);
            }
        });

        jtxtcostofDrinks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtcostofDrinks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcostofDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcostofDrinksActionPerformed(evt);
            }
        });

        jtxtTotalCostofItems.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtTotalCostofItems.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotalCostofItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalCostofItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCostofMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostofDrinks)
                    .addComponent(jiblTotalCostofItems))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtxtCostMeal, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(jtxtcostofDrinks)
                    .addComponent(jtxtTotalCostofItems))
                .addGap(56, 56, 56))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtCostMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostofMeal))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtcostofDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostofDrinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTotalCostofItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jiblTotalCostofItems))
                .addGap(9, 9, 9))
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 510, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
      SubClass_Child ItemCost=new SubClass_Child();
      
      double iTax,iSubTotal,iTotal;
      ItemCost.Filet_O_Fish=ItemCost.pFilet_O_Fish*Double.parseDouble(jtxtFiletofFish.getText());
      ItemCost.ChickenBurger=ItemCost.pChickenBurger*Double.parseDouble(jtxtChickenBurger.getText());
      ItemCost.ChickenLegend=ItemCost.pChickenLegend*Double.parseDouble(jtxtChickenLegend.getText());
      ItemCost.ChickenBurgerM=ItemCost.pChickenBurgerM*Double.parseDouble(jtxtChickenBurgerM.getText());
      ItemCost.BaconCheeseBurger=ItemCost.pBaconCheeseBurger*Double.parseDouble(jtxtBaconandCheeseBurger.getText());
      
       ItemCost.MilkShake=ItemCost.pMilkShake*Double.parseDouble(jtxtMilkShake.getText());
      ItemCost.VanillaCone=ItemCost.pVanillaCone*Double.parseDouble(jtxtVanillaCone.getText());
      ItemCost.ClasVanilla=ItemCost.pClasVanilla*Double.parseDouble(jtxtClasVanilla.getText());
      ItemCost.VanMilkShake=ItemCost.pVanMilkShake*Double.parseDouble(jtxtVanMilkShake.getText());
      ItemCost.ChocMilkShake=ItemCost.pChocMilkShake*Double.parseDouble(jtxtChocMilkShake.getText());    
      
      iSubTotal=ItemCost.GetAmount();
      iTax=ItemCost.cFindTax(iSubTotal);
      iTotal=iSubTotal+iTax;
      
      String SubTotal=String.format("₹%.2f", iSubTotal);
      jtxtSubTotal.setText(SubTotal);
      
      String Tax=String.format("₹%.2f", iTax);
      jtxtTax.setText(Tax);
      
      String Total=String.format("₹%.2f", iTotal);
      jtxtTotal.setText(Total);
      
      String Meal=String.format("₹%.2f", ItemCost.Meals);
      jtxtCostMeal.setText(Meal);
      
     
      String Drink=String.format("₹%.2f", ItemCost.Drinks);
      jtxtcostofDrinks.setText(Drink);
      
      String TotalCost=String.format("₹%.2f", ItemCost.TotalofMD);
      jtxtTotalCostofItems.setText(TotalCost);
      
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
      JTextField cleartext=null;
      
      for(Component c:jPanel6.getComponents()){
           if(c.getClass().toString().contains("javax.swing.JTextField")){
          cleartext=(JTextField)c;
          cleartext.setText("0");
           }
      }
      //==================================================================================
      for(Component c:jPanel4.getComponents()){
          if(c.getClass().toString().contains("javax.swing.JTextField")){
              cleartext=(JTextField)c;
              cleartext.setText("0");
          }
      }
      //==================================================================================
       for(Component c:jPanel11.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
          cleartext=(JTextField)c;
          cleartext.setText("");
      }
       }
      //==================================================================================
      for(Component c:jPanel9.getComponents()){
          if(c.getClass().toString().contains("javax.swing.JTextField")){
              cleartext=(JTextField)c;
              cleartext.setText("");
          }
      }
      //=================================================================================
      jtxtReceipt.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
      SubClass_Child iExit=new SubClass_Child();
      iExit.iExitSystem();
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
       
        int refs=1325 + (int)(Math.random()*4238);
//        ===================================
  Calendar timer=Calendar.getInstance();
  timer.getTime();
  SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
  tTime.format(timer.getTime());
  SimpleDateFormat Tdate=new SimpleDateFormat("dd-MMM-YYYY");
  Tdate.format(timer.getTime());
  
  
  jtxtReceipt.setText("\tRestaurant Management System:\n\n"+
                      "Reference:\t\t\t"+refs+
          "\n===================================\n" +
          "Meals:\t\t" + jtxtCostMeal.getText()+"\n\n"+
          "Drinks:\t\t" + jtxtcostofDrinks.getText()+"\n\n" +
          "Cost of Items:\t" +jtxtTotalCostofItems.getText()+"\n\n"+
          "===================================="+"\n\n"+
          "Tax:\t\t"+jtxtTax.getText()+"\n\n"+
          "Subtotal:\t\t"+jtxtSubTotal.getText()+"\n\n"+
          "Total:\t\t"+jtxtTotal.getText()+"\n"+
          "=============================="+
          "\nDate:"+Tdate.format(timer.getTime())+
          "\tTime: " + tTime.format(timer.getTime())+
          "\n\n\t\tThank you ");
        
        
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMilkShakeActionPerformed

    private void jtxtVanillaConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVanillaConeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVanillaConeActionPerformed

    private void jtxtChocMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChocMilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChocMilkShakeActionPerformed

    private void jtxtVanMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVanMilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVanMilkShakeActionPerformed

    private void jtxtClasVanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtClasVanillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtClasVanillaActionPerformed

    private void jtxtChickenLegendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenLegendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenLegendActionPerformed

    private void jtxtChickenBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenBurgerActionPerformed

    private void jtxtFiletofFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFiletofFishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFiletofFishActionPerformed

    private void jtxtChickenBurgerMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenBurgerMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenBurgerMActionPerformed

    private void jtxtBaconandCheeseBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBaconandCheeseBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBaconandCheeseBurgerActionPerformed

    private void jtxtCostMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostMealActionPerformed

    private void jtxtcostofDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcostofDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcostofDrinksActionPerformed

    private void jtxtTotalCostofItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalCostofItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalCostofItemsActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.IllegalAccessException
     * @throws java.lang.InstantiationException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
  public static void main(String args[]) throws ClassNotFoundException,IllegalAccessException, InstantiationException,  UnsupportedLookAndFeelException{
     //public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OO_Restaurants().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JLabel jiblTotalCostofItems;
    private javax.swing.JLabel jlblBaconandCheeseBurger;
    private javax.swing.JLabel jlblChickenBurger;
    private javax.swing.JLabel jlblChickenBurgerMeal;
    private javax.swing.JLabel jlblChickenLegend;
    private javax.swing.JLabel jlblChocolateMilkShake;
    private javax.swing.JLabel jlblClassicVanilla;
    private javax.swing.JLabel jlblCostofDrinks;
    private javax.swing.JLabel jlblCostofMeal;
    private javax.swing.JLabel jlblDrinks;
    private javax.swing.JLabel jlblFiletOFish;
    private javax.swing.JLabel jlblMeals;
    private javax.swing.JLabel jlblMilkShake;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax2;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblVanillaCone;
    private javax.swing.JLabel jlblVanillaMilkShake;
    private javax.swing.JTextField jtxtBaconandCheeseBurger;
    private javax.swing.JTextField jtxtChickenBurger;
    private javax.swing.JTextField jtxtChickenBurgerM;
    private javax.swing.JTextField jtxtChickenLegend;
    private javax.swing.JTextField jtxtChocMilkShake;
    private javax.swing.JTextField jtxtClasVanilla;
    private javax.swing.JTextField jtxtCostMeal;
    private javax.swing.JTextField jtxtFiletofFish;
    private javax.swing.JTextField jtxtMilkShake;
    private javax.swing.JTextPane jtxtReceipt;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtTotalCostofItems;
    private javax.swing.JTextField jtxtVanMilkShake;
    private javax.swing.JTextField jtxtVanillaCone;
    private javax.swing.JTextField jtxtcostofDrinks;
    // End of variables declaration//GEN-END:variables
}
